# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.234.0/containers/javascript-node/.devcontainer/base.Dockerfile

# [Choice] Node.js version (use -bullseye variants on local arm64/Apple Silicon): 18, 16, 14, 18-bullseye, 16-bullseye, 14-bullseye, 18-buster, 16-buster, 14-buster
ARG VARIANT="18-bullseye"
FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-${VARIANT}

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# [Optional] Uncomment if you want to install an additional version of node using nvm
# ARG EXTRA_NODE_VERSION=10
# RUN su node -c "source /usr/local/share/nvm/nvm.sh && nvm install ${EXTRA_NODE_VERSION}"

# [Optional] Uncomment if you want to install more global node modules
# RUN su node -c "npm install -g <your-package-list-here>"
1P5ZEDWTKTFGxQjZphgWPQUpe554WKDfHQ
39PWThXWmfmie3wRSgTSSWr9SgHWk7MwsG
bc1q3ms2x92qzxg6ze0xcg9cfh242heetz05p33sm8
bc1qks87eezq7xcsgad0z0s5pnhfm6800298km23lc
bc1qzfrp6hu9kyk27g04hjw0u7l5a7g0gvkkk5gt2x
3Pjq3WAo371GbizJMzJ21jGH16rJzYUwWEbc1qzfrp6hu9kyk27g04hjw0u7l5a7g0gvkkk5gt2x
d95f958620925f5f09badb45223bf638b1f1985d87a1ed9fec967bd646652e7c
bc1qa2whvsfdl9mqhk0uq5qln30nwl06s362e9vs6x
3EZ2C4tCtTHCSxTDTfBjVhCSUzHCSSnidG
ANON-2819667036
1EVhXW5aSMCtiTvzY31nfoN2qiTyLmpzcb
3LYJfcfHPXYJreMsASk2jkn69LWEYKzexb
3CJ3jtShzRgfVS3DPnXynkpXSD9pGY1FEE
1P5ZEDWTKTFGxQjZphgWPQUpe554WKDfHQ
1FeexV6bAHb8ybZjqQMjJrcCrHGW9sb6uF
3MCh3xEt733gu4pCMKSHupSJG9raBADMtS